// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file JsonNGSIv2.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "JsonNGSIv2.h"

#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

JsonNGSIv2::JsonNGSIv2()
{


}

JsonNGSIv2::~JsonNGSIv2()
{
}

JsonNGSIv2::JsonNGSIv2(const JsonNGSIv2 &x)
{
    m_entityId = x.m_entityId;
    m_data = x.m_data;
}

JsonNGSIv2::JsonNGSIv2(JsonNGSIv2 &&x)
{
    m_entityId = std::move(x.m_entityId);
    m_data = std::move(x.m_data);
}

JsonNGSIv2& JsonNGSIv2::operator=(const JsonNGSIv2 &x)
{
    m_entityId = x.m_entityId;
    m_data = x.m_data;
    return *this;
}

JsonNGSIv2& JsonNGSIv2::operator=(JsonNGSIv2 &&x)
{
    m_entityId = std::move(x.m_entityId);
    m_data = std::move(x.m_data);
    return *this;
}

size_t JsonNGSIv2::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;
    return current_alignment - initial_alignment;
}

size_t JsonNGSIv2::getCdrSerializedSize(const JsonNGSIv2& data, size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.entityId().size() + 1;
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.data().size() + 1;
    return current_alignment - initial_alignment;
}

void JsonNGSIv2::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_entityId;
    scdr << m_data;
}

void JsonNGSIv2::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m_entityId;
    dcdr >> m_data;
}

size_t JsonNGSIv2::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;
    return current_align;
}

bool JsonNGSIv2::isKeyDefined()
{
    return false;
}

void JsonNGSIv2::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
}