// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file RobotPosition.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "RobotPosition.h"
#include "RobotPositionTypeObject.h"

#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

RobotPosition::RobotPosition()
{
    m_floor = 0;

    m_x = 0;

    m_y = 0;

    m_zeta = 0;


    // Just to register all known types
    registerRobotPositionTypes();
}

RobotPosition::~RobotPosition()
{
}

RobotPosition::RobotPosition(const RobotPosition &x)
{
    m_floor = x.m_floor;
    m_x = x.m_x;
    m_y = x.m_y;
    m_zeta = x.m_zeta;
}

RobotPosition::RobotPosition(RobotPosition &&x)
{
    m_floor = x.m_floor;
    m_x = x.m_x;
    m_y = x.m_y;
    m_zeta = x.m_zeta;
}

RobotPosition& RobotPosition::operator=(const RobotPosition &x)
{
    m_floor = x.m_floor;
    m_x = x.m_x;
    m_y = x.m_y;
    m_zeta = x.m_zeta;

    return *this;
}

RobotPosition& RobotPosition::operator=(RobotPosition &&x)
{
    m_floor = x.m_floor;
    m_x = x.m_x;
    m_y = x.m_y;
    m_zeta = x.m_zeta;

    return *this;
}

size_t RobotPosition::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;

    /* uint32_t */
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    /* uint32_t */
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    /* uint32_t */
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    /* uint32_t */
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t RobotPosition::getCdrSerializedSize(const RobotPosition& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    /* uint32_t floor */
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    /* uint32_t x */
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    /* uint32_t y */
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    /* uint32_t zeta */
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void RobotPosition::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_floor;
    scdr << m_x;
    scdr << m_y;
    scdr << m_zeta;
}

void RobotPosition::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m_floor;
    dcdr >> m_x;
    dcdr >> m_y;
    dcdr >> m_zeta;
}

size_t RobotPosition::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;
            





    return current_align;
}

bool RobotPosition::isKeyDefined()
{
    return false;
}

void RobotPosition::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
	(void) scdr;
	 
	 
	 
	 
}