// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file RobotSnd.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "RobotSnd.h"
#include "RobotSndTypeObject.h"

#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

RobotSnd::RobotSnd()
{




    // Just to register all known types
    registerRobotSndTypes();
}

RobotSnd::~RobotSnd()
{
}

RobotSnd::RobotSnd(const RobotSnd &x)
{
    m_robot_id = x.m_robot_id;
    m_transmission_time = x.m_transmission_time;
    m_position = x.m_position;
}

RobotSnd::RobotSnd(RobotSnd &&x)
{
    m_robot_id = std::move(x.m_robot_id);
    m_transmission_time = std::move(x.m_transmission_time);
    m_position = std::move(x.m_position);
}

RobotSnd& RobotSnd::operator=(const RobotSnd &x)
{
    m_robot_id = x.m_robot_id;
    m_transmission_time = x.m_transmission_time;
    m_position = x.m_position;

    return *this;
}

RobotSnd& RobotSnd::operator=(RobotSnd &&x)
{
    m_robot_id = std::move(x.m_robot_id);
    m_transmission_time = std::move(x.m_transmission_time);
    m_position = std::move(x.m_position);

    return *this;
}

size_t RobotSnd::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;

    /* std::string */
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    /* std::string */
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    /* RobotPosition */
    current_alignment += RobotPosition::getMaxCdrSerializedSize(current_alignment);

    return current_alignment - initial_alignment;
}

size_t RobotSnd::getCdrSerializedSize(const RobotSnd& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;

    /* std::string robot_id */
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.robot_id().size() + 1;

    /* std::string transmission_time */
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.transmission_time().size() + 1;

    /* RobotPosition position */
    current_alignment += RobotPosition::getCdrSerializedSize(data.position(), current_alignment);

    return current_alignment - initial_alignment;
}

void RobotSnd::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_robot_id;
    scdr << m_transmission_time;
    scdr << m_position;
}

void RobotSnd::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m_robot_id;
    dcdr >> m_transmission_time;
    dcdr >> m_position;
}

size_t RobotSnd::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;
            




    return current_align;
}

bool RobotSnd::isKeyDefined()
{
    return false;
}

void RobotSnd::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
	(void) scdr;
	 
	 
	 
}