// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file Header_.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "Header_.h"

#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

std_msgs::msg::dds_::Header_::Header_()
{
    m_sec = 0;
    m_nanosec = 0;

}

std_msgs::msg::dds_::Header_::~Header_()
{
}

std_msgs::msg::dds_::Header_::Header_(const Header_ &x)
{
    m_sec = x.m_sec;
    m_nanosec = x.m_nanosec;
    m_frame_id_ = x.m_frame_id_;
}

std_msgs::msg::dds_::Header_::Header_(Header_ &&x)
{
    m_sec = x.m_sec;
    m_nanosec = x.m_nanosec;
    m_frame_id_ = std::move(x.m_frame_id_);
}

std_msgs::msg::dds_::Header_& std_msgs::msg::dds_::Header_::operator=(const Header_ &x)
{
    m_sec = x.m_sec;
    m_nanosec = x.m_nanosec;
    m_frame_id_ = x.m_frame_id_;
    
    return *this;
}

std_msgs::msg::dds_::Header_& std_msgs::msg::dds_::Header_::operator=(Header_ &&x)
{
    m_sec = x.m_sec;
    m_nanosec = x.m_nanosec;
    m_frame_id_ = std::move(x.m_frame_id_);
    
    return *this;
}

size_t std_msgs::msg::dds_::Header_::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
            
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;


    return current_alignment - initial_alignment;
}

size_t std_msgs::msg::dds_::Header_::getCdrSerializedSize(const std_msgs::msg::dds_::Header_& data, size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
            
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.frame_id_().size() + 1;


    return current_alignment - initial_alignment;
}

void std_msgs::msg::dds_::Header_::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_sec;

    scdr << m_nanosec;

    if(m_frame_id_.length() <= 255)
    scdr << m_frame_id_;
    else
        throw eprosima::fastcdr::exception::BadParamException("frame_id_ field exceeds the maximum length");
}

void std_msgs::msg::dds_::Header_::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m_sec;
    dcdr >> m_nanosec;
    dcdr >> m_frame_id_;
}

size_t std_msgs::msg::dds_::Header_::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;
            




    return current_align;
}

bool std_msgs::msg::dds_::Header_::isKeyDefined()
{
    return false;
}

void std_msgs::msg::dds_::Header_::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
	 
	 
	 
}


