// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file Output.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "Output.h"

#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

Output::Output()
{
    m_time = 0.0;
    m_rotation = 0.0;
}

Output::~Output()
{
}

Output::Output(const Output &x)
{
    m_time = x.m_time;
    m_rotation = x.m_rotation;
}

Output::Output(Output &&x)
{
    m_time = x.m_time;
    m_rotation = x.m_rotation;
}

Output& Output::operator=(const Output &x)
{
    m_time = x.m_time;
    m_rotation = x.m_rotation;
    
    return *this;
}

Output& Output::operator=(Output &&x)
{
    m_time = x.m_time;
    m_rotation = x.m_rotation;
    
    return *this;
}

size_t Output::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
            
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

size_t Output::getCdrSerializedSize(const Output& data, size_t current_alignment)
{
    size_t initial_alignment = current_alignment;
            
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

void Output::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_time;

    scdr << m_rotation;

}

void Output::deserialize(eprosima::fastcdr::Cdr &dcdr)
{
    dcdr >> m_time;
    dcdr >> m_rotation;
}

size_t Output::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
	size_t current_align = current_alignment;
            



    return current_align;
}

bool Output::isKeyDefined()
{
    return false;
}

void Output::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
	 
	 
}