// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file RobotRcvTypeObject.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _ROBOTRCV_TYPE_OBJECT_H_
#define _ROBOTRCV_TYPE_OBJECT_H_

#include "RobotPositionTypeObject.h"

#include <fastrtps/types/TypeObject.h>
#include <map>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(RobotRcv_SOURCE)
#define RobotRcv_DllAPI __declspec( dllexport )
#else
#define RobotRcv_DllAPI __declspec( dllimport )
#endif // RobotRcv_SOURCE
#else
#define RobotRcv_DllAPI
#endif
#else
#define RobotRcv_DllAPI
#endif // _WIN32

using namespace eprosima::fastrtps::types;

eProsima_user_DllExport void registerRobotRcvTypes();

eProsima_user_DllExport const TypeIdentifier* GetStateIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetStateObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalStateObject();
eProsima_user_DllExport const TypeObject* GetCompleteStateObject();

eProsima_user_DllExport const TypeIdentifier* GetRobotRcvIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetRobotRcvObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalRobotRcvObject();
eProsima_user_DllExport const TypeObject* GetCompleteRobotRcvObject();


#endif // _ROBOTRCV_TYPE_OBJECT_H_