// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file JsonNGSIv2PubSubTypes.h
 * This header file contains the declaration of the serialization functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#ifndef _JSONNGSIV2_PUBSUBTYPES_H_
#define _JSONNGSIV2_PUBSUBTYPES_H_

#include <fastrtps/TopicDataType.h>

#include "JsonNGSIv2.h"

/*!
 * @brief This class represents the TopicDataType of the type JsonNGSIv2 defined by the user in the IDL file.
 * @ingroup JSONNGSIV2
 */
class JsonNGSIv2PubSubType : public eprosima::fastrtps::TopicDataType
{
public:
	typedef JsonNGSIv2 type;

    eProsima_user_DllExport JsonNGSIv2PubSubType();
    eProsima_user_DllExport virtual ~JsonNGSIv2PubSubType();
    eProsima_user_DllExport bool serialize(void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload);
    eProsima_user_DllExport bool deserialize(eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data);
        std::function<uint32_t()> getSerializedSizeProvider(void* data);
    eProsima_user_DllExport bool getKey(void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5 = false);
    eProsima_user_DllExport void* createData();
    eProsima_user_DllExport void deleteData(void * data);

	MD5 m_md5;
	unsigned char* m_keyBuffer;
};

#endif // _JsonNGSIv2_PUBSUBTYPE_H_